version: "3"
services:

  db:
    image: postgres:13
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: db
      POSTGRES_PASSWORD: cloudbalance
    volumes:
      - pgstore:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6.2-rc1
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server

volumes:
  pgstore:
  redisdata:


