"""transactions_timestamp

Revision ID: d47a397059e4
Revises: 57548778462f
Create Date: 2021-03-03 02:01:36.044544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47a397059e4'
down_revision = '57548778462f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'timestamp')
    # ### end Alembic commands ###
